import { CatDetailsData } from "./Types";

export const MockCatDetailData: CatDetailsData[] = [
	{
		id: "beng",
		name: "Bengal",
		temperament: "Alert, Agile, Energetic, Demanding, Intelligent",
		origin: "United States",
		description:
			"Bengals are a lot of fun to live with, but they're definitely not the cat for everyone, or for first-time cat owners. Extremely intelligent, curious and active, they demand a lot of interaction and woe betide the owner who doesn't provide it.",
		life_span: "12 - 15",
		adaptability: 5,
		affection_level: 5,
		child_friendly: 4,
		grooming: 1,
		health_issues: 3,
		intelligence: 5,
		social_needs: 5,
		stranger_friendly: 3,
		wikipedia_url: "https://en.wikipedia.org/wiki/Bengal_(cat)",
		image: {
			id: "O3btzLlsO",
			width: 1100,
			height: 739,
			url: "https://cdn2.thecatapi.com/images/O3btzLlsO.png",
		},
	},
	{
		id: "birm",
		name: "Birman",
		temperament: "Alert, Agile, Energetic, Demanding, Intelligent",
		origin: "United States",
		description:
			"Bengals are a lot of fun to live with, but they're definitely not the cat for everyone, or for first-time cat owners. Extremely intelligent, curious and active, they demand a lot of interaction and woe betide the owner who doesn't provide it.",
		life_span: "12 - 15",
		adaptability: 5,
		affection_level: 5,
		child_friendly: 4,
		grooming: 1,
		health_issues: 3,
		intelligence: 5,
		social_needs: 5,
		stranger_friendly: 3,
		wikipedia_url: "https://en.wikipedia.org/wiki/Bengal_(cat)",
		image: {
			id: "O3btzLlsO",
			width: 1100,
			height: 739,
			url: "https://cdn2.thecatapi.com/images/HOrX5gwLS.jpg",
		},
	},
	{
		id: "bomb",
		name: "Bombay",
		temperament: "Alert, Agile, Energetic, Demanding, Intelligent",
		origin: "United States",
		description:
			"Bengals are a lot of fun to live with, but they're definitely not the cat for everyone, or for first-time cat owners. Extremely intelligent, curious and active, they demand a lot of interaction and woe betide the owner who doesn't provide it.",
		life_span: "12 - 15",
		adaptability: 5,
		affection_level: 5,
		child_friendly: 4,
		grooming: 1,
		health_issues: 3,
		intelligence: 5,
		social_needs: 5,
		stranger_friendly: 3,
		wikipedia_url: "https://en.wikipedia.org/wiki/Bengal_(cat)",
		image: {
			id: "O3btzLlsO",
			width: 1100,
			height: 739,
			url: "https://cdn2.thecatapi.com/images/5iYq9NmT1.jpg",
		},
	},
	{
		id: "bslo",
		name: "British Longhair",
		temperament: "Alert, Agile, Energetic, Demanding, Intelligent",
		origin: "United States",
		description:
			"Bengals are a lot of fun to live with, but they're definitely not the cat for everyone, or for first-time cat owners. Extremely intelligent, curious and active, they demand a lot of interaction and woe betide the owner who doesn't provide it.",
		life_span: "12 - 15",
		adaptability: 5,
		affection_level: 5,
		child_friendly: 4,
		grooming: 1,
		health_issues: 3,
		intelligence: 5,
		social_needs: 5,
		stranger_friendly: 3,
		wikipedia_url: "https://en.wikipedia.org/wiki/Bengal_(cat)",
		image: {
			id: "O3btzLlsO",
			width: 1100,
			height: 739,
			url: "https://cdn2.thecatapi.com/images/7isAO4Cav.jpg",
		},
	},
];
